# Generated by Django 3.2.20 on 2023-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appt_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(default='Appt')),
                ('date', models.DateTimeField(null=True)),
                ('video_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(max_length=10)),
                ('date', models.DateTimeField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Other_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(default='Other')),
                ('date', models.DateTimeField(null=True)),
                ('video_status', models.IntegerField(default=0)),
                ('form1', models.TextField(default='未回答', max_length=500)),
                ('form2_name', models.TextField(default='未回答', max_length=50)),
                ('form2_address', models.TextField(default='未回答', max_length=50)),
                ('form3', models.TextField(default='未回答', max_length=10)),
                ('form4_date', models.TextField(default='未回答', max_length=20)),
                ('form4_day', models.TextField(default='未回答', max_length=20)),
                ('form4_weather', models.TextField(default='未回答', max_length=20)),
                ('form4_transportation', models.TextField(default='未回答', max_length=50)),
                ('form4_trivia', models.TextField(default='未回答', max_length=300)),
                ('form4_message', models.TextField(default='未回答', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(default='Owner')),
                ('location', models.TextField(null=True)),
                ('update_url_text', models.IntegerField(default='11')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Time_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(default='Owner')),
                ('start_date', models.DateField(null=True, verbose_name='日付')),
                ('start_time', models.TimeField(null=True, verbose_name='時刻')),
                ('finish_date', models.DateField(null=True, verbose_name='日付')),
                ('finish_time', models.TimeField(null=True, verbose_name='時刻')),
            ],
        ),
        migrations.CreateModel(
            name='Post_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(max_length=10)),
                ('date', models.DateTimeField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('visitor', models.TextField(max_length=10)),
                ('date', models.DateTimeField(null=True)),
                ('message', models.TextField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_Message_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(max_length=10)),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
