# Generated by Django 3.2.20 on 2023-08-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Message_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(max_length=20)),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
