# Generated by Django 3.2.20 on 2023-08-04 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_visitor_message_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appt_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(default='Owner')),
                ('location', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Time_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(default='Owner')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visitor_message_db',
            name='message',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor_message_db',
            name='visitor',
            field=models.TextField(max_length=10),
        ),
    ]
