# Generated by Django 3.2.20 on 2023-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_alter_delivery_db_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_db',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='delivery'),
        ),
    ]
