# Generated by Django 3.2.20 on 2023-08-04 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_alter_delivery_db_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(default='Other')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_status', models.IntegerField(default=0)),
                ('form1', models.TextField(default='null', max_length=500)),
                ('fomr2_name', models.TextField(default='null', max_length=50)),
                ('fomr2_address', models.TextField(default='null', max_length=50)),
                ('fomr2_contact', models.TextField(default='null', max_length=50)),
                ('form3', models.TextField(default='null', max_length=10)),
                ('form4_date', models.TextField(max_length=20)),
                ('form4_day', models.TextField(max_length=20)),
                ('form4_weather', models.TextField(max_length=20)),
                ('form4_transportation', models.TextField(max_length=50)),
                ('form4_trivia', models.TextField(max_length=300)),
                ('form4_message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.TextField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
    ]
