# Generated by Django 3.2.20 on 2023-08-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_other_db_post_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_db',
            name='fomr2_address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='fomr2_contact',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='fomr2_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='form1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='form3',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='owner_db',
            name='location',
            field=models.TextField(),
        ),
    ]
