# Generated by Django 3.2.20 on 2023-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0011_auto_20230804_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_db',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
