# Generated by Django 3.2.20 on 2023-09-02 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0012_alter_post_db_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt_db',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 23, 28, 10, 308025)),
        ),
        migrations.AlterField(
            model_name='appt_db',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 23, 28, 10, 308039)),
        ),
        migrations.AlterField(
            model_name='delivery_db',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 23, 28, 10, 308300)),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 23, 28, 10, 308954)),
        ),
        migrations.AlterField(
            model_name='post_db',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 23, 28, 10, 308675)),
        ),
        migrations.AlterField(
            model_name='visitor_db',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 23, 28, 10, 307556)),
        ),
        migrations.AlterField(
            model_name='visitor_db',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
