# Generated by Django 3.2.20 on 2023-09-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0013_auto_20230902_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt_db',
            name='finish_date',
        ),
        migrations.AlterField(
            model_name='appt_db',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delivery_db',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post_db',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor_db',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
