# Generated by Django 3.2.20 on 2023-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0014_auto_20230903_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt_db',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery_db',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='other_db',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post_db',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor_db',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
