# Generated by Django 3.2.20 on 2023-09-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0015_auto_20230903_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_db',
            name='form2_contact',
        ),
    ]
