# Generated by Django 3.2.20 on 2023-09-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0017_visitor_db_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt_db',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
