# Generated by Django 3.2.20 on 2023-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0018_alter_appt_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appt_db',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
