# Generated by Django 3.2.20 on 2023-09-21 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0019_alter_appt_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_time_db',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='finish_date',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='start_date',
            field=models.TimeField(null=True),
        ),
    ]
