# Generated by Django 3.2.20 on 2023-09-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0020_auto_20230921_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_time_db',
            name='date',
            field=models.DateField(),
        ),
    ]
