# Generated by Django 3.2.20 on 2023-09-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0021_alter_owner_time_db_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_time_db',
            name='date',
        ),
        migrations.AddField(
            model_name='owner_time_db',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='owner_time_db',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
