# Generated by Django 3.2.20 on 2023-10-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0022_auto_20230921_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_time_db',
            name='finish_date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='finish_time',
            field=models.TimeField(null=True, verbose_name='時刻'),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='start_date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='owner_time_db',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='時刻'),
        ),
        migrations.AlterField(
            model_name='visitor_message_db',
            name='message',
            field=models.TextField(max_length=50),
        ),
    ]
