# Generated by Django 3.2.20 on 2023-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0024_owner_db_update_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_db',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='owner_db',
            name='update_url_text',
            field=models.IntegerField(default='0', max_length=8),
        ),
    ]
