# Generated by Django 3.2.20 on 2023-10-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0025_auto_20231006_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_db',
            name='update_url_text',
            field=models.IntegerField(default='00', max_length=8),
        ),
    ]
