# Generated by Django 3.2.20 on 2023-10-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0026_alter_owner_db_update_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_db',
            name='update_url_text',
            field=models.IntegerField(default='11'),
        ),
    ]
